################################################################
## Packages / Studio
##   Studio ISY-994 lights, switches, and scenes
##   Studio Media Players
##   Studio Groups and Backyard Group
################################################################

################################################################
## Customize
################################################################
homeassistant:
  customize:
    ################################################
    ## Media Player
    ################################################
    media_player.studio:
      friendly_name: "DirecTV Studio"
    media_player.apple_tv_studio:
      friendly_name: "Apple TV Studio"
    media_player.sonos_studio:
      friendly_name: "Sonos Studio"

    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.studio_front_door_sensor:
      friendly_name: "Studio Door"
      device_class: door

    ################################################
    ## Light
    ################################################
    light.studio_chandeliers_door:
      friendly_name: "Studio Chandeliers"
      icon: mdi:ceiling-light
    light.studio_bed_fan_light:
      friendly_name: "Studio Bedroom Light"
    light.studio_bath_light_door:
      friendly_name: "Studio Bathroom Light"
    light.studio_kitchen_chandelier:
      friendly_name: "Studio Kitchen Chandelier"
      icon: mdi:ceiling-light
    light.studio_kitchen_sink_lights:
      friendly_name: "Studio Kitchen Sink Lights"
      icon: mdi:ceiling-light
    light.studio_kitchen_cabinet_lights:
      friendly_name: "Studio Kitchen Cabinet Lights"
    light.studio_beam_fan_light:
      friendly_name: "Studio Beam Fan Light"
      icon: mdi:ceiling-light
    light.studio:
      friendly_name: "Studio Fan Light"
      icon: mdi:ceiling-light
    light.studio_vault_fan_light:
      friendly_name: "Studio Vault Fan Light"
      icon: mdi:ceiling-light

    ################################################
    ## Switch
    ################################################
    # scene
    switch.studio_chandeliers:
      friendly_name: "Studio Chandeliers"
      icon: mdi:ceiling-light
    switch.studio_shoplights:
      friendly_name: "Studio Shoplights"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_a:
      friendly_name: "Studio Shoplight A"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_b:
      friendly_name: "Studio Shoplight B"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_c:
      friendly_name: "Studio Shoplight C"
      icon: mdi:spotlight-beam
    switch.studio_shoplight_d:
      friendly_name: "Studio Shoplight D"
      icon: mdi:spotlight-beam
    switch.studio_kitchen_lights:
      friendly_name: "Studio Kitchen Lights"
      icon: mdi:lightbulb
    switch.studio_bed_light:
      friendly_name: "Studio Bedroom Light"
      icon: mdi:lightbulb
    switch.studio_bath_light:
      friendly_name: "Studio Bathroom Light"
      icon: mdi:lightbulb
    switch.studio_bath_vent_fan:
      friendly_name: "Studio Bathroom Fan"
      icon: mdi:fan
    switch.studio_loft_light:
      friendly_name: "Studio Loft Light"
      icon: mdi:lightbulb

    ################################################
    ## Fan
    ################################################
    fan.studio:
      friendly_name: "Studio Fan"
    fan.studio_vault_fan:
      friendly_name: "Studio Vault Fan"
    fan.studio_beam_fan:
      friendly_name: "Studio Beam Fan"
    fan.studio_bed_fan:
      friendly_name: "Studio Bedroom Fan"
    fan.studio_loft_fan:
      friendly_name: "Studio Loft Fan"

    ################################################
    ## Remote
    ################################################
    remote.studio:
      friendly_name: "Studio Harmony Remote"

################################################################
## Group
################################################################
group:
  # Studio ISY-994 group
  studio:
    name: Studio
    control: hidden
    entities:
      - light.studio_chandeliers_door
      - light.studio_kitchen_chandelier
      - switch.studio_shoplights
      - switch.studio_shoplight_a
      - switch.studio_shoplight_b
      - switch.studio_shoplight_c
      - switch.studio_shoplight_d
      - fan.studio_vault_fan
      - light.studio_vault_fan_light
      - fan.studio_beam_fan
      - light.studio_beam_fan_light

  # Studio Kitchen ISY-994 group
  studio_kitchen:
    name: Studio Kitchen
    control: hidden
    entities:
      - switch.studio_kitchen_lights
      - light.studio_kitchen_chandelier
      - light.studio_kitchen_cabinet_lights
      - light.studio_kitchen_sink_lights

  # Studio Bedroom ISY-994 group
  studio_bed:
    name: Studio Bedroom
    control: hidden
    entities:
      - switch.studio_bed_light
      - fan.studio_bed_fan
      - switch.studio_bath_light
      - switch.studio_bath_fan

  # Studio Loft ISY-994 group
  studio_loft:
    name: Studio Loft
    control: hidden
    entities:
      - switch.studio_loft_light
      - fan.studio_loft_fan

  # Studio Media Players
  studio_media:
    name: Studio Media
    control: hidden
    entities:
      - media_player.studio
      - media_player.apple_tv_studio
      - media_player.sonos_studio

  # Studio Climate group
  studio_climate:
    name: Studio Climate
    control: hidden
    entities:
      - climate.studio
      - sensor.studio_cool_hours_yesterday
      - sensor.studio_heat_hours_yesterday

################################################################
## Sensor
################################################################
sensor:
  # accumulates the time the Studio AC has been cooling yesterday
  - platform: history_stats
    name: Studio Cool Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'cooling'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  # accumulates the time the Studio AC has been heating yesterday
  - platform: history_stats
    name: Studio Heat Hours Yesterday
    entity_id: sensor.studio_thermostat_hvac_state
    state: 'heating'
    type: time
    # all of yesterday
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24
